# Define el pipeline DVC para el modelo de PREDICCIÓN de probabilidad de compra

stages:
  load:
    cmd: python3 src/load_data.py --config params.yaml
    deps:
      - src/load_data.py
      - params.yaml
    outs:
      - data/processed/initial_sales_clean.parquet:
          persist: true # Queremos guardar esta salida intermedia

  preprocess:
    cmd: python3 src/preprocess.py --config params.yaml
    deps:
      - src/preprocess.py
      - data/processed/initial_sales_clean.parquet
      - params.yaml
    outs:
      - data/processed/daily.parquet:
          persist: true

  featurize:
    cmd: python3 src/featurize.py --config params.yaml
    deps:
      - src/featurize.py
      - data/processed/daily.parquet
    params:
      - data.base_path
      - data.processed_folder
      - preprocess.daily_output_file
      - featurize
    outs:
      - data/processed/calendar_features.parquet:
          persist: true

  train:
    cmd: python3 src/train.py --config params.yaml
    deps:
      - src/train.py
      - data/processed/calendar_features.parquet
    params:
      - base.random_state
      - data.base_path
      - data.processed_folder
      - featurize.output_file
      - train
      - model
    outs:
      # Salida: el modelo entrenado (sin calibrar)
      - models/model.joblib:
          persist: true

  evaluate:
    cmd: python3 src/evaluate.py --config params.yaml
    deps:
      - src/evaluate.py
      - models/model.joblib
      - data/processed/calendar_features.parquet
    params:
      - base.random_state
      - data.base_path
      - data.processed_folder
      - train # Necesita parámetros de features, target, split_days
      - featurize.output_file
      - model
      - evaluate
      - reports
    metrics:
      - reports/metrics.json:
          cache: false # No cachear para ver diffs en git
    plots:
      - reports/plots/calibration_curve.png:
          cache: false
      - reports/plots/feature_importance.png:
          cache: false
      - reports/plots/shap_summary.png:
          cache: false
    outs:
      - models/calibrated_model.joblib:
          persist: true # Guardar modelo calibrado
      - reports/classification_report_base.txt:
          cache: false
      - reports/classification_report_calibrated.txt:
          cache: false

  backtest:
    cmd: python3 src/backtest.py --config params.yaml
    deps:
      - src/backtest.py
      - models/calibrated_model.joblib
      - data/processed/calendar_features.parquet
      #- data/raw/ventas_backtesting_new.csv
    params:
      - data.base_path
      - data.processed_folder
      - featurize.output_file
      - model.model_dir
      - model.calibrated_model_name
      - evaluate.evaluation_threshold
      - backtesting
      - reports.reports_dir
      - reports.backtesting_metrics_file
      - train.features
    outs:
      - reports/backtesting_metrics.csv:
          cache: false # No cachear para ver diffs en git